try:
    print(x)

except:
    print("error occured")
finally:
    print("success")